#DH xx.12.2016
#This ansible playbook will download and install checkMK on your raspbery pi. 
#It is not perfect .. but its something.
#Thanks to https://mirzadedic.ca/node/23 for fixing the problem with snap7 package
---
- name: Deploy CheckMK-RAW on an raspberry pi
  hosts: m05mon01
  vars:
     hostname: m05mon01
     packages_to_install:
     - aptitude
     - unattended-upgrades
     - openssh-server
     - htop
     - iftop 
     - check-mk-agent
     optional_packages_to_install:
     - python-ldap 
     - build-essential 
     - patch 
     - fping 
     - smbclient  
     - rpcbind  
     - dnsutils  
     - git-buildpackage 
     - libboost-all-dev 
     - libcurl4-openssl-dev  
     - libcloog-ppl1       
     - libncurses5-dev     
     - libdbi-dev 
     - libevent-dev 
     - libgd-dev 
     - libglib2.0-dev 
     - libgnutls28-dev 
     - libldap2-dev 
     - libltdl-dev 
     - libmcrypt-dev 
     - libmysqlclient15-dev 
     - libpq-dev 
     - libpango1.0-dev 
     - libperl-dev 
     - libreadline6-dev 
     - libssl-dev 
     - libxml2-dev 
     - patch 
     - python-dev 
     - python-setuptools  
     - uuid-dev 
     - snmp 
     - apache2-threaded-dev   
     - apache2                
     - libfreeradius-client-dev 
     - dietlibc-dev  
     - libpcap-dev  
     - gettext  
     - libgsf-1-dev  
     - librrd-dev 
     - libapache2-mod-fcgid
     - php5
     - xinetd
     - dialog

     path_for_check_mk_package: /root/check-mk-raw-1.2.8p14.cre
     path_for_snap7_package: /root/check-mk-raw-1.2.8p14.cre/packages/snap7/snap7-full-1.3.0.tar.gz
     dest_path_for_snap7_package: /root/check-mk-raw-1.2.8p14.cre/packages/snap7/
     filename_for_check_mk_source_package: check-mk-raw-1.2.8p14.cre.tar.gz
     filename_for_check_mk_precompiled_package: check-mk-raw-1.2.8p14.cre-compiled.tar.gz
     path_for_auth_ssh_keys: authorized_keys

  tasks:
  - name: download check-mk-raw source code
    get_url:
      url: https://mathias-kettner.de/support/1.2.8p14/check-mk-raw-1.2.8p14.cre.tar.gz  
      dest: /root/{{ filename_for_check_mk_source_package }}
      checksum: sha256:0cbb93536985e1608805f479552b733136752c2a0a420200e85cfb58ebc8172a
 
  - name: check python is installed in container
    raw: dpkg -s python
    register: python_install_check
    failed_when: python_install_check.rc not in [0, 1]
    changed_when: false
#pretask
  - name: install python in container
    raw: apt-get install -y python
    when: python_install_check.rc == 1

  - name: Create the .ssh directory
    file: path=/root/.ssh state=directory
  
  - name: Push SSH Config to container
    copy:
      src: "{{ path_for_auth_ssh_keys }}"
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root
      mode: 0600

  - name: Update old packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 3600

  - name: Install APT packages in the container
    apt: 
      name={{ item }} state=latest update_cache=yes cache_valid_time=3600
    with_items: "{{ packages_to_install }}"
  
  - name: Install optional APT packages in the container
    apt: 
      name={{ item }} state=latest update_cache=yes cache_valid_time=3600
    with_items: "{{ optional_packages_to_install }}"

  - name: copy CheckMK Source to the Raspberry pi
    copy:
      src: ./files/{{ filename_for_check_mk_source_package }}
      dest: /root/{{ filename_for_check_mk_source_package }}
      owner: root
      group: root

  - name: unarchive the packge
    unarchive:
      src: /root/{{ filename_for_check_mk_source_package }}
      dest: /root/
      remote_src: yes

  - name: unarchive CUZ BUG
    unarchive:
      src: "{{ path_for_snap7_package }}"
      dest: "{{ dest_path_for_snap7_package }}"
      remote_src: yes

  - name: because dima is doing hacks
    shell: 
      cmd: cp arm_v7_linux.mk armv7l_linux.mk
      chdir: "{{ path_for_check_mk_package }}/packages/snap7/snap7-full-1.3.0/build/unix/"

  - name: run configure
    shell:
      cmd: bash configure
      chdir: "{{ path_for_check_mk_package }}"
     
  - name: run make
    shell:
      cmd: make
      chdir: "{{ path_for_check_mk_package }}"
  
  - name: because dima is doing more hacks. because is know stuff.
    shell: 
      cmd: cp -r arm_v7-linux armv7l-linux
      chdir: "{{ path_for_check_mk_package }}/packages/snap7/snap7-full-1.3.0/build/bin/"

  - name: run make pack
    shell:
      cmd: make pack
      chdir: "{{ path_for_check_mk_package }}"

  - name: run make setup
    shell:
      cmd: make setup
      chdir: "{{ path_for_check_mk_package }}"

  - name: Create the group 
    group:
      name: omd
      state: present

  - name: Create CheckMK Site
    command: omd create "{{ hostname }}"
    register: checkmkstart

  - name: Because DH wants it that way
    shell:
      cmd: cp /etc/apache2/conf.d/zzz_omd.conf /etc/apache2/conf-available/zzz_omd.conf

  - name: Because DH wants it that way
    shell:
      cmd: a2enconf zzz_omd.conf
  
  - name: Enable Apache2 modules
    apache2_module:
      state: present
      name: proxy_http

  - name: Enable TCP port for live monitoring
    command: omd omd config "{{ hostname }}" set LIVESTATUS_TCP ON 

  - name: Start CheckMK Site
    command: omd start "{{ hostname }}"

  - debug: var=checkmkstart.stdout_lines
